### PR TITLE
Add support for capi-aws-nodelet

### PR DESCRIPTION
**Pull request by Rohitrajak1807**
- add supporting manifests for nodelet
- add aws-capi-nodelet as a valid combination for validation functions

### CODE REVIEW

**Review by cruizen — DISMISSED** [review]
Looks good. 

Is there a task to insert the identityRef for cloud provider in ArlonCtl?

**Comment by Rohitrajak1807** [comment]
> Looks good.
> 
> Is there a task to insert the identityRef for cloud provider in ArlonCtl?

Yes, AFAIK @jayanth-tjvrr is working on it currently.

**Review by cruizen — APPROVED** [review]
Approving again. Ensure that we have deployed a cluster manually using the nodelet provider. Attach a screenshot if it's readily available.

**Comment by Rohitrajak1807** [comment]
Merging

**Pull request merged**
