### PR TITLE
Added documentation for `arlon cluster ngupdate` command in the readme file

### PR DESCRIPTION
**Pull request by jayanth-tjvrr**
Fixes : https://github.com/arlonproj/arlon/issues/249 
The readme file now includes instructions for the `arlon cluster ngupdate` command which is used to update the profiles in next-gen arlon clusters.

### CODE REVIEW

**Review by Rohitrajak1807 — APPROVED** [review]

**Comment by cruizen** [comment]
@jayanth-tjvrr can you please make the same change(s) in docs/README.md too?

**Review by cruizen — CHANGES_REQUESTED** [review]
@jayanth-tjvrr can you please make the same change(s) in docs/README.md too?

**Comment by cruizen** [comment]
> @jayanth-tjvrr can you please make the same change(s) in docs/README.md too?

@jayanth-tjvrr I have updated docs/README.md

**Review by cruizen — APPROVED** [review]
LGTM.

**Comment by jayanth-tjvrr** [comment]
> > @jayanth-tjvrr can you please make the same change(s) in docs/README.md too?
> 
> @jayanth-tjvrr I have updated docs/README.md

Thanks @cruizen!

**Pull request merged**
