### PR TITLE
Modify basecluster configuration for capa v2.0

### PR DESCRIPTION
**Pull request by ShaunakJoshi1407**
Fixes: https://github.com/arlonproj/arlon/issues/329

####  As per capa v2.0 changes, now `AWSManagedCluster` is reintroduced : 
https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.0.0
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3797

### MachineDeployment Cluster (CAPA v2..0.1)
Screenshot 2022-11-24 at 11 48 23 AM

Screenshot 2022-11-24 at 11 48 47 AM

### MachinePool Cluster ( CAPA v2.0.1)
Screenshot 2022-11-24 at 11 40 23 AM

Screenshot 2022-11-24 at 11 42 32 AM

### MachineDeployment Cluster (CAPA v1.5.1)
Screenshot 2022-11-24 at 10 28 57 AM

Screenshot 2022-11-24 at 10 43 11 AM

### MachinePool Cluster ( CAPA v1.5.1)
Screenshot 2022-11-24 at 10 37 27 AM

Screenshot 2022-11-24 at 10 42 35 AM

### CODE REVIEW

**Comment by cruizen** [comment]
@ShaunakJoshi1407 e2e tests are failing with the latest CAPA. This PR update will help fix that. Please also update the assertion in the e2e test and update `arlon verify` to check that CAPA installed has a supported version.

**Comment by ShaunakJoshi1407** [comment]
e2e tests are passing with this change: https://github.com/arlonproj/arlon/actions/runs/3533781035

**Review by bcle — APPROVED** [review]
Looks good, but does that mean that any v1beta1 manifest will fail?

**Comment by ShaunakJoshi1407** [comment]
> Looks good, but does that mean that any v1beta1 manifest will fail?

I was thinking about adding the older v1beta1 references in the configurations.yaml and testing out with CAPA v2.0 and CAPA v1.5. If cluster creation is successful in both of these cases, then I will go forward and commit it here

**Comment by ShaunakJoshi1407** [comment]
@bcle @cruizen  I have verified that with the presence of both `v1beta1` and `v1beta2` apiVersions in configurations.yaml, we can still use older CAPA versions to generate manifests and create arlon clusters using these manifests. I have added the screenshots for the same in the PR description. Do take a look.

**Comment by ShaunakJoshi1407** [comment]
e2e tests are also passing with this change in configurations.yaml

**Review by cruizen — APPROVED** [review]
LGTM. Thanks for making the changes. See if any changes are required to the docs.

**Pull request merged**
