### PR TITLE
support for managing external clusters (issue #23)

### PR DESCRIPTION
**Pull request by bcle**
This change allows arlon to manage external clusters that it did not create, but are registered in argocd. A user specifies a profile when requesting to manage an external cluster. Design details:
- "Internal" clusters (created by arlon) are backed by ArgoCD applications with certain arlon labels & annotations. Those apps manage the top-level root application for the cluster.
- External clusters do not have a top-level cluster application. They are identified by labeling the ArgoCD secret containing the cluster information, with an arlon-specific label.
- The new `cluster.List()` and `cluster.Get()` functions return a Cluster struct that has a `IsExternal` flag. If the flag is true, another field identifies the name of the corresponding ArgoCD secret. The `arlon cluster list` command now shows the flag in the cluster list.
- To manage an external cluster, the user runs `arlon cluster manage <clusterName> <profileName>` to apply the specified profile to the cluster. The user can switch to a different profile with `arlon cluster update <clusterName> --profile <newProfileName>`. The cluster is unmanaged with `arlon cluster unmanage <clusterName>`.
- When an external cluster is managed, an ArgoCD application is created for the dynamic profile bound to the cluster. Only dynamic profiles are supported at this point.

### CODE REVIEW

**Comment by cre8minus1** [comment]
@bcle @chinmaykolhatkar is the a 0.3.0 item?

**Comment by cre8minus1** [comment]
@bcle is this related to #23

**Comment by bcle** [comment]
> @bcle is this related to #23

Yes. Linked the PR to this issue.

**Review by cruizen — APPROVED** [review]
The code change is fine. This change is for v0.9 and not v0.3, right? 
We need to change the `version` file on main branch in that case - or any branch that we intend to merge into main.

**Comment by cruizen** [comment]
I think this content is missing in the docs (README) right now. Once we reorganise the docs, it should go into a tutorial / command reference page. Not sure if we mention the external clusters capability in the docs.

**Pull request merged**
